---
abstract: 'supply F<termios(3)> methods to C<IO::Handle> objects'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  IO::Pty: 0
  IO::Tty: 0
  Test::LongString: 0
  Test::More: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4202, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IO-Termios
provides:
  IO::Termios:
    file: lib/IO/Termios.pm
    version: 0.04
requires:
  IO::Tty: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
